FROM golang
WORKDIR /go/src/github.com/openshift
RUN git clone https://github.com/openshift/ci-search \
    && cd ci-search \
    && grep -rl test-platform-results . | xargs sed -i 's/test-platform-results/kubernetes-ci-logs/g' \
    && grep -rl "OpenShift" . | xargs sed -i 's/OpenShift/Kubernetes-ppc64le/g' \
    && grep -rl "prow\.ci\.openshift\.org" . | xargs sed -i 's/prow\.ci\.openshift\.org/prow\.k8s\.io/g' \
    && GO_BUILD_PACKAGES=./cmd/search make GO_REQUIRED_MIN_VERSION:= build

FROM quay.io/centos/centos:stream9
COPY --from=0 /go/src/github.com/openshift/ci-search/search /usr/bin/
RUN curl -L https://github.com/BurntSushi/ripgrep/releases/download/12.0.1/ripgrep-12.0.1-x86_64-unknown-linux-musl.tar.gz | \
    tar xvzf - --wildcards --no-same-owner --strip-components=1  -C /usr/bin '*/rg'
RUN mkdir /var/lib/ci-search && chown 1000:1000 /var/lib/ci-search && chmod 1777 /var/lib/ci-search
USER 1000:1000
ENTRYPOINT ["search"]
CMD ["--path=/var/lib/ci-search/", "--deck-uri=https://prow.k8s.io"]
EXPOSE 8080
