{
 "title": "PowerVM OCP4 Scale Job Status",
 "description": "Provides build health stats for each project_name in an org",
 "time": { "from": "now-1y", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "project_name",
    "query": "SHOW TAG VALUES FROM jenkins_data WITH KEY = \"project_name\""
   }
  ]
 },
 "panels": [
  { "title": "Notice Board", "type": "text", "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 } },
  {
   "title": "Note",
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "options": {
    "content": "<font color=\"#2AB608\" size=\"3\">NS</font>  <font size=\"3\"> --> Number of Namespaces created </font> <br />\n<font color=\"#2AB608\" size=\"3\">NS.R.Time</font>  <font size=\"3\"> --> Real time taken for creating Namespaces </font><br />\n<font color=\"#2AB608\" size=\"3\">DS</font>  <font size=\"3\"> --> Number of Deployments created </font><br />\n<font color=\"#2AB608\" size=\"3\">DS.R.Time</font>  <font size=\"3\"> --> Real time taken for creating Deploymnets </font> <br />\n"
   },
   "content": "<font color=\"#2AB608\" size=\"3\">NS</font>  <font size=\"3\"> --> Number of Namespaces created </font> <br />\n<font color=\"#2AB608\" size=\"3\">NS.R.Time</font>  <font size=\"3\"> --> Real time taken for creating Namespaces </font><br />\n<font color=\"#2AB608\" size=\"3\">DS</font>  <font size=\"3\"> --> Number of Deployments created </font><br />\n<font color=\"#2AB608\" size=\"3\">DS.R.Time</font>  <font size=\"3\"> --> Real time taken for creating Deploymnets </font> <br />\n"
  },
  { "title": "JOB: $project_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "project_name" },
  {
   "title": "Latest Build",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "jenkins_data",
     "select": [
      [
       { "params": [ "build_result_ordinal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Latest Openshift Build",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "clusterinfo",
     "select": [
      [
       { "params": [ "ocp_build" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Build",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "jenkins_data",
     "select": [
      [
       { "params": [ "build_time" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Overall Build Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 4 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "Passed",
     "measurement": "jenkins_data",
     "query": "SELECT count(\"jobtime\") FROM \"job\" WHERE (\"project_name\" =~ /^$project_name$/ AND \"result\" = 'CompletedSuccess') AND $timeFilter",
     "select": [
      [
       { "params": [ "build_time" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project_name$/" },
      { "condition": "AND", "key": "build_result", "operator": "=", "value": "SUCCESS" }
     ]
    },
    {
     "alias": "Failed",
     "measurement": "jenkins_data",
     "query": "SELECT count(\"build_time\") FROM \"autogen\".\"jenkins_data\" WHERE (\"project_name\" =~ /^$project_name$/ AND \"build_result\" = 'FAILURE') AND $timeFilter",
     "select": [
      [
       { "params": [ "build_time" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project_name$/" },
      { "condition": "AND", "key": "build_result", "operator": "=", "value": "FAILURE" }
     ]
    },
    {
     "alias": "Unstable",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"build_time\") FROM \"autogen\".\"jenkins_data\" WHERE (\"project_name\" =~ /^$project_name$/ AND \"build_result\" = 'UNSTABLE') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Aborted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"build_time\") FROM \"autogen\".\"jenkins_data\" WHERE (\"project_name\" =~ /^$project_name$/ AND \"build_result\" = 'ABORTED') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Build Details",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"time\", \"project_name\",  \"coreos_build\", \"ocp_build\", \"build_number\", \"server_type\", \"master_node_cpu\", \"master_node_mem\", \"worker_node_cpu\", \"worker_node_mem\", \"namespaces\", \"real_time_namespace\", \"user_time_namespace\", \"system_time_namespace\",  \"deployments\", \"real_time_deployments\", \"user_time_deployments\", \"system_time_deployments\"  FROM \"clusterinfo\" WHERE (\"project_name\" =~ /^$project_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "measurement": "jenkins_data",
     "query": "SELECT  \"build_result_ordinal\", \"project_path\"   FROM \"autogen\".\"jenkins_data\"  WHERE (\"project_name\" =~ /^$project_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "tests_failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project_name$/" }
     ]
    }
   ]
  }
 ]
}