presubmits:
  ppc64le-cloud/test-infra:
    - name: presubmit-allinone-job
      labels:
        preset-image-builder: "true"
      decorate: true
      branches:
        - '.*'
      always_run: true
      # run_if_changed: 'images/all-in-one'
      spec:
        serviceAccountName: build-img
        containers:
          - image: quay.io/powercloud/all-in-one:0.7
            command:
              - /bin/bash
            args:
              - -c
              - |
                set -o errexit
                set -o nounset
                set -o pipefail
                set -o xtrace

                pushd images/all-in-one

                export version=$(cat version.txt)

                docker build -t quay.io/powercloud/all-in-one:$version-amd64 -f Dockerfile ./
                docker build -t quay.io/powercloud/all-in-one:$version-ppc64le -f Dockerfile ./

                docker run --rm quay.io/powercloud/all-in-one:$version-amd64 /bin/bash -c "echo 'Testing AMD64 image'"
                docker run --rm quay.io/powercloud/all-in-one:$version-ppc64le /bin/bash -c "echo 'Testing PPC64LE image'"

                docker rmi quay.io/powercloud/all-in-one:$version-amd64
                docker rmi quay.io/powercloud/all-in-one:$version-ppc64le

                echo "Presubmit job succeeded: Docker images validated successfully."
