# This file contains all the required spec for service account, roles and role bindings for the monitor-prow-controller pod
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: prow
  name: "monitor-prow-controller"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prow
  name: "monitor-prow-controller"
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments/scale
    verbs:
      - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prow
  name: "monitor-prow-controller"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "monitor-prow-controller"
subjects:
  - kind: ServiceAccount
    name: "monitor-prow-controller"
    namespace: prow
