postsubmits:
  ocp-power-automation/openshift-install-power:
    - name: openshift-install-power-build-and-push-on-release
      labels:
        preset-image-builder: "true"
      decorate: true
      always_run: true
      branches:
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      extra_refs:
        - base_ref: v0.1.2
          org: vmware-tanzu
          repo: buildkit-cli-for-kubectl
      spec:
        serviceAccountName: build-img
        containers:
          - image: quay.io/powercloud/all-in-one:0.7
            command:
              - /bin/bash
            args:
              - -c
              - |
                set -o errexit
                set -o nounset
                set -o pipefail
                pushd $GOPATH/src/github.com/vmware-tanzu/buildkit-cli-for-kubectl
                make build install
                popd
                ca=$(base64 -w 0 /run/secrets/kubernetes.io/serviceaccount/ca.crt)
                token=$(cat /run/secrets/kubernetes.io/serviceaccount/token)
                namespace=$(cat /run/secrets/kubernetes.io/serviceaccount/namespace)
                cat >kubeconfig <<EOL
                apiVersion: v1
                kind: Config
                clusters:
                - name: default-cluster
                  cluster:
                    certificate-authority-data: ${ca}
                    server: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT_HTTPS}
                contexts:
                - name: default-context
                  context:
                    cluster: default-cluster
                    namespace: ${namespace}
                    user: default-user
                current-context: default-context
                users:
                - name: default-user
                  user:
                    token: ${token}
                EOL
                export KUBECONFIG=$(pwd)/kubeconfig
                for version in 4.11 4.12 4.13 4.14
                do
                    kubectl build --push --registry-secret quay-powercloud-regcred --namespace image-builder --build-arg RELEASE_VER=$version -t quay.io/powercloud/openshift-install-powervs:ocp$version-amd -t quay.io/powercloud/openshift-install-powervs:$PULL_BASE_REF-ocp$version-amd -f images/Dockerfile ./
                    kubectl build --push --registry-secret quay-powercloud-regcred --kubeconfig /etc/kubeconfig/config --namespace image-builder --build-arg RELEASE_VER=$version -t quay.io/powercloud/openshift-install-powervs:ocp$version-ppc64le -t quay.io/powercloud/openshift-install-powervs:$PULL_BASE_REF-ocp$version-ppc64le -f images/Dockerfile ./
                done
                curl -L https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-`go env GOARCH` -o /usr/local/bin/manifest-tool
                chmod +x /usr/local/bin/manifest-tool
                cat > config.json << EOL
                $DOCKER_CONFIG
                EOL
                for version in 4.11 4.12 4.13 4.14
                do
                cat > registry.yaml <<EOL
                image: quay.io/powercloud/openshift-install-powervs:ocp$version
                tags: ['$PULL_BASE_REF-ocp$version', 'latest']
                manifests:
                  -
                    image: quay.io/powercloud/openshift-install-powervs:ocp$version-ppc64le
                    platform:
                      architecture: ppc64le
                      os: linux
                  -
                    image: quay.io/powercloud/openshift-install-powervs:ocp$version-amd
                    platform:
                      architecture: amd64
                      os: linux
                EOL
                manifest-tool --debug --docker-cfg `pwd` push from-spec registry.yaml
                done
